cask "font-harmonyos-sans" do
  version :latest
  sha256 :no_check

  url "https://developer.huawei.com/images/download/next/HarmonyOS-Sans.zip"
  name "HarmonyOS Sans"
  desc "Huawei HarmonyOS Sans font"
  homepage "https://developer.huawei.com/consumer/cn/design/resource/"

  font "HarmonyOS Sans /HarmonyOS_Sans/HarmonyOS_Sans_Black.ttf"
  font "HarmonyOS Sans /HarmonyOS_Sans/HarmonyOS_Sans_Bold.ttf"
  font "HarmonyOS Sans /HarmonyOS_Sans/HarmonyOS_Sans_Light.ttf"
  font "HarmonyOS Sans /HarmonyOS_Sans/HarmonyOS_Sans_Medium.ttf"
  font "HarmonyOS Sans /HarmonyOS_Sans/HarmonyOS_Sans_Regular.ttf"
  font "HarmonyOS Sans /HarmonyOS_Sans/HarmonyOS_Sans_Thin.ttf"
  font "HarmonyOS Sans /HarmonyOS_Sans_Condensed/HarmonyOS_Sans_Condensed_Black.ttf"
  font "HarmonyOS Sans /HarmonyOS_Sans_Condensed/HarmonyOS_Sans_Condensed_Bold.ttf"
  font "HarmonyOS Sans /HarmonyOS_Sans_Condensed/HarmonyOS_Sans_Condensed_Light.ttf"
  font "HarmonyOS Sans /HarmonyOS_Sans_Condensed/HarmonyOS_Sans_Condensed_Medium.ttf"
  font "HarmonyOS Sans /HarmonyOS_Sans_Condensed/HarmonyOS_Sans_Condensed_Regular.ttf"
  font "HarmonyOS Sans /HarmonyOS_Sans_Condensed/HarmonyOS_Sans_Condensed_Thin.ttf"
  font "HarmonyOS Sans /HarmonyOS_Sans_Condensed_Italic/HarmonyOS_Sans_Condensed_Black_Italic.ttf"
  font "HarmonyOS Sans /HarmonyOS_Sans_Condensed_Italic/HarmonyOS_Sans_Condensed_Bold_Italic.ttf"
  font "HarmonyOS Sans /HarmonyOS_Sans_Condensed_Italic/HarmonyOS_Sans_Condensed_Light_Italic.ttf"
  font "HarmonyOS Sans /HarmonyOS_Sans_Condensed_Italic/HarmonyOS_Sans_Condensed_Medium_Italic.ttf"
  font "HarmonyOS Sans /HarmonyOS_Sans_Condensed_Italic/HarmonyOS_Sans_Condensed_Regular_Italic.ttf"
  font "HarmonyOS Sans /HarmonyOS_Sans_Condensed_Italic/HarmonyOS_Sans_Condensed_Thin_Italic.ttf"
  font "HarmonyOS Sans /HarmonyOS_Sans_Italic/HarmonyOS_Sans_Black_Italic.ttf"
  font "HarmonyOS Sans /HarmonyOS_Sans_Italic/HarmonyOS_Sans_Bold_Italic.ttf"
  font "HarmonyOS Sans /HarmonyOS_Sans_Italic/HarmonyOS_Sans_Light_Italic.ttf"
  font "HarmonyOS Sans /HarmonyOS_Sans_Italic/HarmonyOS_Sans_Medium_Italic.ttf"
  font "HarmonyOS Sans /HarmonyOS_Sans_Italic/HarmonyOS_Sans_Regular_Italic.ttf"
  font "HarmonyOS Sans /HarmonyOS_Sans_Italic/HarmonyOS_Sans_Thin_Italic.ttf"
  font "HarmonyOS Sans /HarmonyOS_Sans_Naskh_Arabic/HarmonyOS_Sans_Naskh_Arabic_Black.ttf"
  font "HarmonyOS Sans /HarmonyOS_Sans_Naskh_Arabic/HarmonyOS_Sans_Naskh_Arabic_Bold.ttf"
  font "HarmonyOS Sans /HarmonyOS_Sans_Naskh_Arabic/HarmonyOS_Sans_Naskh_Arabic_Light.ttf"
  font "HarmonyOS Sans /HarmonyOS_Sans_Naskh_Arabic/HarmonyOS_Sans_Naskh_Arabic_Medium.ttf"
  font "HarmonyOS Sans /HarmonyOS_Sans_Naskh_Arabic/HarmonyOS_Sans_Naskh_Arabic_Regular.ttf"
  font "HarmonyOS Sans /HarmonyOS_Sans_Naskh_Arabic/HarmonyOS_Sans_Naskh_Arabic_Thin.ttf"
  font "HarmonyOS Sans /HarmonyOS_Sans_SC/HarmonyOS_SansSC_Black.ttf"
  font "HarmonyOS Sans /HarmonyOS_Sans_SC/HarmonyOS_SansSC_Bold.ttf"
  font "HarmonyOS Sans /HarmonyOS_Sans_SC/HarmonyOS_SansSC_Light.ttf"
  font "HarmonyOS Sans /HarmonyOS_Sans_SC/HarmonyOS_SansSC_Medium.ttf"
  font "HarmonyOS Sans /HarmonyOS_Sans_SC/HarmonyOS_SansSC_Regular.ttf"
  font "HarmonyOS Sans /HarmonyOS_Sans_SC/HarmonyOS_SansSC_Thin.ttf"
  font "HarmonyOS Sans /HarmonyOS_Sans_TC/HarmonyOS_SansTC_Black.ttf"
  font "HarmonyOS Sans /HarmonyOS_Sans_TC/HarmonyOS_SansTC_Bold.ttf"
  font "HarmonyOS Sans /HarmonyOS_Sans_TC/HarmonyOS_SansTC_Light.ttf"
  font "HarmonyOS Sans /HarmonyOS_Sans_TC/HarmonyOS_SansTC_Medium.ttf"
  font "HarmonyOS Sans /HarmonyOS_Sans_TC/HarmonyOS_SansTC_Regular.ttf"
  font "HarmonyOS Sans /HarmonyOS_Sans_TC/HarmonyOS_SansTC_Thin.ttf"

  # No zap stanza required
end
