cask "font-honor-sans" do
  version "1.2"
  sha256 "8c7eb6f940479343eea7c18745f2d66679fb853100a32591ea68bf62fd734fb6"

  url "https://contentplatform-drcn.hihonorcdn.com/developerPlatform/HONOR_Sans_#{version}/HONOR_Sans_#{version}.zip"
  name "HONOR Sans"
  desc "Honor Sans font"
  homepage "https://developer.honor.com/cn/doc/guides/100681"

  font "HONOR_Sans_1.2/HONORSans/HONORSans-Bold.ttf"
  font "HONOR_Sans_1.2/HONORSans/HONORSans-Demibold.ttf"
  font "HONOR_Sans_1.2/HONORSans/HONORSans-ExtraBold.ttf"
  font "HONOR_Sans_1.2/HONORSans/HONORSans-ExtraLight.ttf"
  font "HONOR_Sans_1.2/HONORSans/HONORSans-Heavy.ttf"
  font "HONOR_Sans_1.2/HONORSans/HONORSans-Light.ttf"
  font "HONOR_Sans_1.2/HONORSans/HONORSans-Medium.ttf"
  font "HONOR_Sans_1.2/HONORSans/HONORSans-Regular.ttf"
  font "HONOR_Sans_1.2/HONORSans/HONORSans-Thin.ttf"
  font "HONOR_Sans_1.2/HONORSansArabic/HONORSansArabicUI-B.ttf"
  font "HONOR_Sans_1.2/HONORSansArabic/HONORSansArabicUI-DB.ttf"
  font "HONOR_Sans_1.2/HONORSansArabic/HONORSansArabicUI-EB.ttf"
  font "HONOR_Sans_1.2/HONORSansArabic/HONORSansArabicUI-EL.ttf"
  font "HONOR_Sans_1.2/HONORSansArabic/HONORSansArabicUI-H.ttf"
  font "HONOR_Sans_1.2/HONORSansArabic/HONORSansArabicUI-L.ttf"
  font "HONOR_Sans_1.2/HONORSansArabic/HONORSansArabicUI-M.ttf"
  font "HONOR_Sans_1.2/HONORSansArabic/HONORSansArabicUI-R.ttf"
  font "HONOR_Sans_1.2/HONORSansArabic/HONORSansArabicUI-T.ttf"
  font "HONOR_Sans_1.2/HONORSansCN/HONORSansCN-Bold.ttf"
  font "HONOR_Sans_1.2/HONORSansCN/HONORSansCN-DemiBold.ttf"
  font "HONOR_Sans_1.2/HONORSansCN/HONORSansCN-ExtraBold.ttf"
  font "HONOR_Sans_1.2/HONORSansCN/HONORSansCN-ExtraLight.ttf"
  font "HONOR_Sans_1.2/HONORSansCN/HONORSansCN-Heavy.ttf"
  font "HONOR_Sans_1.2/HONORSansCN/HONORSansCN-Light.ttf"
  font "HONOR_Sans_1.2/HONORSansCN/HONORSansCN-Medium.ttf"
  font "HONOR_Sans_1.2/HONORSansCN/HONORSansCN-Regular.ttf"
  font "HONOR_Sans_1.2/HONORSansCN/HONORSansCN-Thin.ttf"
  font "HONOR_Sans_1.2/HONORSansTC/HONORSansTC-Bold.ttf"
  font "HONOR_Sans_1.2/HONORSansTC/HONORSansTC-DemiBold.ttf"
  font "HONOR_Sans_1.2/HONORSansTC/HONORSansTC-ExtraBold.ttf"
  font "HONOR_Sans_1.2/HONORSansTC/HONORSansTC-ExtraLight.ttf"
  font "HONOR_Sans_1.2/HONORSansTC/HONORSansTC-Heavy.ttf"
  font "HONOR_Sans_1.2/HONORSansTC/HONORSansTC-Light.ttf"
  font "HONOR_Sans_1.2/HONORSansTC/HONORSansTC-Medium.ttf"
  font "HONOR_Sans_1.2/HONORSansTC/HONORSansTC-Regular.ttf"
  font "HONOR_Sans_1.2/HONORSansTC/HONORSansTC-Thin.ttf"

  # No zap stanza required
end
